config/rbac/role.yaml, controllers/application_controller.go
This will fix the following error:
```
E0204 01:40:30.942946       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1alpha1.Application: failed to list *v1alpha1.Application: applications.argoproj.io is forbidden: User "system:serviceaccount:argocd-commenter-system:default" cannot list resource "applications" in API group "argoproj.io" at the cluster scope
```
=> Fix cluster role of controller-manager

controllers/applicationhealthstatus_controller.go, controllers/argocd.go
Eventually the controller posts duplicated comments for health of a revision. It should use `Status.OperationState.Operation.Sync.Revision` instead of `Status.Sync.Revision`.
=> Fix duplicated healthy notifications

controllers/annotation.go
The controller caused a crash loop due to the following error:
```
panic: assignment to entry in nil map
goroutine 310 [running]:
github.com/int128/argocd-commenter/controllers.(*ApplicationHealthStatusReconciler).Reconcile.func1(0xc000293180)
/workspace/controllers/applicationhealthstatus_controller.go:57 +0x45
github.com/int128/argocd-commenter/controllers.patchAnnotation({_, _}, {_, _}, {{{0x19a656a, 0xb}, {0xc0031791b8, 0x14}}, {{0xc003293dd4, 0x9}, ...}, ...}, ...)
/workspace/controllers/annotation.go:20 +0x1c3
github.com/int128/argocd-commenter/controllers.(*ApplicationHealthStatusReconciler).Reconcile(0xc0009fa120, {0x2116e78, 0xc003ae5200}, {{{0xc003293dea, 0x1ce94c0}, {0xc003293dd4, 0xc00066c680}}})
/workspace/controllers/applicationhealthstatus_controller.go:56 +0x1f3 …
```
=> Fix nil panic if Application has no annotations

pkg/github/comment.go, pkg/github/pull.go, pkg/github/types.go, pkg/notification/comment.go
This adds a feature to determine if a pull request is related to a sync or healthy event. It will prevent a comment to unrelated pull request.
=> Filter pull requests by changed files on comment

README.md
Hey folks
Many thanks for this project - looks awesome!
I followed the README which still installs a very old version 0.3.0 - so I hit some bugs that were already fixed. It would be cool if we could bump the link in the README, so that the newest version is installed.
=> bump deployment manifest to release 1.8.0

go.mod, pkg/notification/comment.go, pkg/notification/event.go, pkg/notification/event_test.go, pkg/notification/types.go
Follow up https://github.com/int128/argocd-commenter/pull/656.
This extracts `GetManifestGeneratePaths()` function and adds tests.
=> refactor: extract `GetManifestGeneratePaths()` and add tests

.github/workflows/docker.yaml, e2e_test/Makefile, e2e_test/applications/app3.yaml, e2e_test/applications/kustomization.yaml, e2e_test/fixture/Makefile, e2e_test/fixture/app3/cronjob/echoserver.yaml, e2e_test/fixture/app3/kustomization.yaml, e2e_test/fixture/app3/namespace/app3.yaml
This adds a test case for a resource which does not trigger "progressing" state, such as `CronJob`.
Currently, the deployment is not changed to "Active" state.
=> Add test of no-progressing resource

.github/workflows/docker.yaml, pkg/notification/deployment.go
Some resources (such as CronJob or ConfigMap) do not trigger Progressing status. Consequently, the deployment is still in-progress after deploy.
When an application is successfully synced and healthy, it changes the deployment to success.
It seems no problem to determine if an application is healthy when sync phase is changed, because the health status is updated in the sync operation.
https://github.com/argoproj/gitops-engine/blob/v0.7.3/pkg/sync/sync_context.go#L407-L438
=> Fix deployment did not become Active for CronJob

controllers/applicationhealthchange_controller.go
if the update operation is failed, it notifies more than once. To avoid conflict, it would be nice to patch.
=> Patch last healthy instead of update

.github/workflows/docker.yaml, e2e_test/Makefile
Currently the deployment statuses become "Destroyed" after the E2E test.
It would be nice if we can see the final status.
=> Keep final deployment status in E2E test

pkg/notification/deployment.go
It eventually notifies a deployment status of success before an application is progressing.
1. Application phase is running
2. Application phase is succeeded and application is healthy
3. Application is progressing
4. Application is healthy
Step 2 and 3 are triggered in very short time.
Revert https://github.com/int128/argocd-commenter/pull/727.
If an application has only non-workload resource (such as ConfigMap or CronJob), it does not notify a deployment status of success.
=> Revert #727: Fix deployment did not become Active for CronJob

api/v1/applicationhealth_types.go, config/crd/bases/argocdcommenter.int128.github.io_applicationhealths.yaml, controllers/applicationhealthdeployment_controller.go, controllers/applicationhealthdeployment_controller_test.go, controllers/applicationphasedeployment_controller.go, controllers/applicationphasedeployment_controller_test.go, controllers/mocks_test.go, controllers/suite_test.go, pkg/github/deployment.go, pkg/github/types.go, pkg/notification/deployment.go, pkg/notification/types.go
This fixes the edge case of https://github.com/int128/argocd-commenter/issues/762#issuecomment-1304465447.
It removes `lastHealthyDeploymentURL` field. Instead, it checks the current deployment status from GitHub API.
=> Check the current deployment status from GitHub API

go.mod, pkg/github/client.go
Follow up #801. This will mitigate the rate limit of GitHub API.
=> Enable HTTP cache for GitHub API

controllers/applicationhealthdeployment_controller.go, controllers/applicationhealthdeployment_controller_test.go, controllers/applicationphasedeployment_controller.go, pkg/argocd/application.go
When an invalid GitHub Deployment is set in an Application, this controller will retry the notification forever. It may cause the rate limit of GitHub API.
Set a timeout.
=> Set retry timeout on deployment not found error

.github/workflows/docker.yaml
Follow up https://github.com/int128/argocd-commenter/pull/813.
=> Extend timeout of docker build

.github/renovate.json5
Reverts int128/argocd-commenter#829.
It did not work.
https://github.com/int128/argocd-commenter/pull/793#issuecomment-1369441772
```
Command failed: docker run --rm --name=renovate_sidecar --label=renovate_child -v "/mnt/renovate/gh/int128/argocd-commenter":"/mnt/renovate/gh/int128/argocd-commenter" -v "/tmp/renovate-cache":"/tmp/renovate-cache" -v "/tmp/containerbase":"/tmp/containerbase" -e GOPATH -e GOPROXY -e GOFLAGS -e CGO_ENABLED -e GIT_CONFIG_KEY_0 -e GIT_CONFIG_VALUE_0 -e GIT_CONFIG_KEY_1 -e GIT_CONFIG_VALUE_1 -e GIT_CONFIG_KEY_2 -e GIT_CONFIG_VALUE_2 -e GIT_CONFIG_COUNT -e BUILDPACK_CACHE_DIR -e CONTAINERBASE_CACHE_DIR -w "/mnt/renovate/gh/int128/argocd-commenter" docker.io/renovate/sidecar bash -l -c "install-tool golang 1.19.4 && go get -d -t ./... && go mod tidy && go mod …
```
=> Revert "Enable gomodMassage in Renovate"

.github/workflows/docker.yaml
Currently it takes too long time to build.
e.g., https://github.com/int128/argocd-commenter/actions/runs/3835027973
=> Do not build arm64 image

.dockerignore, .gitignore, Makefile, config/crd/bases/argocdcommenter.int128.github.io_applicationhealths.yaml, config/crd/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml, config/rbac/role.yaml, internal/controller/suite_test.go
- Upgrade from kubebuilder v3.10.0 to v3.11.0
- Upgrade from kubebuilder v3.11.0 to v3.11.1
=> Upgrade to kubebuilder v3.11.1

e2e_test/applications/app1.yaml, e2e_test/applications/app3.yaml, e2e_test/waitforapp/main.go, internal/argocd/application.go, internal/controller/applicationhealthcomment_controller.go, internal/controller/applicationphasecomment_controller.go, internal/notification/comment.go
- https://github.com/int128/argocd-commenter/issues/893
- https://github.com/int128/argocd-commenter/issues/849
=> Support multiple sources and revisions

.github/workflows/docker.yaml
Replace with https://github.com/actions/create-github-app-token
=> Use actions/create-github-app-token

internal/notification/client.go, internal/notification/healthcomment.go, internal/notification/phasecomment.go, internal/notification/pull.go, internal/notification/pull_test.go
When an application has multiple sources, the controller does not create a comment to the related pull requests.
Fix https://github.com/int128/argocd-commenter/issues/1021.
=> Fix pull request comment for multiple sources

internal/notification/healthdeployment.go, internal/notification/phasedeployment.go
Enables full support for External URL's in Argo CD. 
Otherwise it will throw error during updating deployment status.
I'm not go developer(but java), please check if it ok from go perspective.
I'm providing my verbal approve to edit this PR by maintainers in order to merge it as fast as possible.
Thanks!
=> Add full support for Argo CD external urls
