int128/argocd-commenter

.github/workflows/e2e-test.yaml, .gitignore, e2e_test/Makefile, e2e_test/applications/helloworld.yaml, e2e_test/applications/kustomization.yaml, e2e_test/argocd/kustomization.yaml, e2e_test/argocd/namespace/argocd.yaml, e2e_test/argocd/statefulset/argocd-application-controller.yaml, e2e_test/controller/deployment/argocd-commenter-controller-manager.yaml, e2e_test/controller/kustomization.yaml, e2e_test/helloworld/deployment/echoserver.yaml, e2e_test/helloworld/kustomization.yaml, e2e_test/helloworld/namespace/helloworld.yaml, e2e_test/wait-for-synced.sh
This will add the end-to-end test with ArgoCD and this repository.
=> Add E2E test

e2e_test/helloworld/deployment/echoserver.yaml
This is created by e2e-test of #0
=> e2e-test: sync failure

README.md
Before:
https://github.com/yuya-takeyama-test-org/settings/apps/new?name=argocd-commenter&url=https://github.com/int128/argocd-commenter&webhook_active=false&pull_requests=write
After:
https://github.com/organizations/yuya-takeyama-test-org/settings/apps/new?name=argocd-commenter&url=https://github.com/int128/argocd-commenter&webhook_active=false&pull_requests=write
=> Fix URL for organizations

README.md
This will fix https://github.com/int128/argocd-commenter/issues/192.
=> Add contents read-only permission to GitHub App

config/manager/manager.yaml
- Don't limit cpu resource
- Set memory request = limit
=> Fix resources for production ready

.github/workflows/manifest.yaml
https://github.com/int128/hide-comment-action
=> Add hide-comment-action

PROJECT, controllers/annotation.go, controllers/applicationhealthstatus_controller.go, main.go
- kubebuilder create api --group argocdcommenter --version v1 --kind ApplicationHealthStatus
- Post health status comment
=> Post health status comment

controllers/applicationhealthstatus_controller.go
=> Fix duplicated healthy notifications

pkg/github/types.go, pkg/github/types_test.go
- https://github.com/int128/argocd-commenter/issues/641
=> Parse SSH repository URL

pkg/notification/comment.go
Argo CD defines [argocd.argoproj.io/manifest-generate-paths](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#webhook-and-manifest-paths-annotation) annotation to specify the paths that are used to generate an application's manifest.
> The argocd.argoproj.io/manifest-generate-paths contains a semicolon-separated list of paths within the Git repository that are used during manifest generation.
This pull request takes into account that annotation to determine more accurately whether a pull request is related to an application event and thus whether a comment should be made or not. 
This is useful when manifests are generated based on files from different folders.
Here is an example of a mono-repository folder structure illustrating such a use case:
```
.
├── …
```
=> Support Manifest Paths annotation when determining related pull requests

PROJECT, controllers/applicationhealthcomment_controller.go, controllers/applicationhealthdeployment_controller.go, controllers/argocd.go, controllers/suite_test.go, main.go, pkg/notification/deployment.go
Fix https://github.com/int128/argocd-commenter/issues/692.
=> Notify deployment status once

.github/workflows/docker.yaml
=> Fix e2e-test on tag push

config/default/manager_auth_proxy_patch.yaml, controllers/suite_test.go
https://github.com/int128/hello-kubebuilder/pull/4/commits/e7921bbe47a5c309811c13441905af24b4a86dbe
=> Apply patch to kubebuilder v3.6.0

controllers/applicationhealthdeployment_controller.go, controllers/applicationhealthdeployment_controller_test.go
Fix https://github.com/int128/argocd-commenter/issues/762#issuecomment-1279599989.
=> Retry until Application is synced with valid Deployment URL

PROJECT, controllers/applicationphasecomment_controller.go, controllers/applicationphasecomment_controller_test.go, controllers/applicationphasedeployment_controller.go, controllers/applicationphasedeployment_controller_test.go, controllers/mocks_test.go, controllers/suite_test.go, main.go
- refactor: split ApplicationPhaseCommentReconciler and ApplicationPhaseDeploymentReconciler
- Don't notify deployment status if already healthy
- Refactor
=> Don't notify deployment status if already healthy

controllers/applicationhealthdeployment_controller_test.go, controllers/applicationphasedeployment_controller_test.go, controllers/mocks_test.go
Add the test cases for https://github.com/int128/argocd-commenter/issues/762.
=> Test when application became healthy before annotation is updated

pkg/github/client.go
- https://github.com/int128/argocd-commenter/issues/865
=> Support GitHub App token on GitHub Enterprise server

go.mod, go.sum
```sh
go mod tidy -go=1.21.0
```
=> Bump go.mod to 1.21

internal/controller/applicationhealthcomment_controller.go
Fix https://github.com/int128/argocd-commenter/issues/1087
=> Increase requeueTimeToEvaluateHealthStatusAfterSyncOperation

.gitignore, Dockerfile, Makefile, cmd/main.go, config/crd/bases/argocdcommenter.int128.github.io_applicationhealths.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/applicationhealth_editor_role.yaml, config/rbac/applicationhealth_viewer_role.yaml, config/rbac/auth_proxy_client_clusterrole.yaml, config/rbac/auth_proxy_role.yaml, config/rbac/auth_proxy_role_binding.yaml, config/rbac/auth_proxy_service.yaml, config/rbac/kustomization.yaml, config/rbac/leader_election_role.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml, internal/controller/suite_test.go
Pick https://github.com/int128/kubebuilder-updates/pull/91/commits/c8557394e1fcde80414693650806199b837d5f0b
=> Upgrade from kubebuilder v3.13.0 to v3.14.2

go.mod
```console
% go list -m all
go: k8s.io/cri-client@v0.0.0: invalid version: unknown revision v0.0.0
```
=> Fix go.mod replace
